### ISSUE TITLE
[BE] CRON Jobs

### ISSUE THREAD

**Issue by farahwamer** [queens-psyc-clinic/app#136]
Use APScheduler to have CRON jobs that occur every (day, or couple of hours) to schedule functions that need to happen on a regular basis like: 

Might have to add an **isConfirmed** column to loans table

- Daily it should sift through all signed out items (loan table) and see what is overdue and notify these people

- Daily it should sift through items and check what is low on stock and email admins who are subscribed to notifications

- Daily backup of table 

-  every two hours it should check to see if reserved items have been picked up, otherwise, unreserve them (increment stock again) (NO NEED TO DO THIS ONE)

**Comment by cainsusk** [comment]
This is mainly just to backup the database, but it could be expanded
