### ISSUE TITLE
[FE FIX] Make tests top-level instead of items

### ISSUE THREAD

**Issue by cainsusk** [queens-psyc-clinic/app#99]
**Admin:** 
- [x] make tests top level in chart
- [x] add accordion out listing all its components
- [x] ensure it opens on click only

**Client:**
- [x] make tests top level in cards
- [x] list components in the modal in the form of a checklist
- [x] ensure users can "check off" items they want to add to cart
- [x] ensure users can select all

**Other notes:**
Ensure signed in and out pages still item based so make a new table component for this accordion feature!

**Comment by manda-02** [comment]
admin side is done in #116
